# This dockerfile provides an example of using the production image in a working stack
version: '2'

services:

  mysql:
    container_name: semaphore_db
    image: mysql:5.6
    hostname: mysql
    env_file:
      - stack.env
    networks:
      - semaphore
    volumes:
      - semaphore-db:/var/lib/mysql

  semaphore:
    container_name: semaphore_ui
    image: semaphoreui/semaphore:latest
    depends_on:
      - mysql
    env_file:
      - stack.env
    networks:
      - semaphore

  semaphore_proxy:
    container_name: semaphore_proxy
    image: ansiblesemaphore/proxy:latest
    build:
      context: ./proxy
    depends_on:
      - semaphore
    networks:
      - semaphore
      - reverseproxy

volumes:
  semaphore-db:
    external: true

networks:
  reverseproxy:
    external: true
  semaphore:
    external: true
